coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 60%
        threshold: 5%
        base: auto
    patch:
      default:
        target: 60%
        whreshold: 5%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "**/*.md"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.toml"
