coverage:
  precision: 2
  round: down
  range: "50...100"
  if_ci_failed: success
  status:
    project:
      default:
        target: 60%
        threshold: 20%
    patch:
      default:
        target: 60%
        threshold: 20%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  hide_project_coverage: false # set to false

ignore:
  - "tests/"
  - "**/*.md"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.toml"
